[phases.setup]
nixPkgs = ["python313", "poetry"]

[phases.install]
cmds = ["poetry install --no-dev --no-root"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
